[workspace]
resolver = "2"

members = [
    "ruwm",
    "ruwm-esp32",
]

[patch.crates-io]
#atomic-polyfill = { git = "https://github.com/esp-rs-compat/atomic-polyfill" }
#critical-section = { git = "https://github.com/esp-rs-compat/critical-section" }
#embassy = { git = "https://github.com/embassy-rs/embassy" }
#embedded-svc = { path = "../embedded-svc" }
#esp-idf-hal = { path = "../esp-idf-hal" }
#esp-idf-svc = { path = "../esp-idf-svc" }

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
