[package]
name = "ruwm"
version = "0.1.0"
authors = ["ivmarkov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["hal", "embedded"]
description = "A library of subsystems for a water meter controller."
repository = "https://github.com/ivmarkov/esp32-water-meter"
readme = "README.md"

[features]
default = ["experimental"]

experimental = ["embedded-svc/experimental"]

[dependencies]
anyhow = "1"
log = "0.4"
futures = {version = "0.3", features = ["async-await"] }
embedded-hal = "0.2"
embedded-svc = "0.16.8"
embedded-graphics = "0.7"
profont = "0.5"
