[package]
name = "ruwm-esp32"
version = "0.1.0"
authors = ["ivmarkov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["hal", "embedded"]
description = "A binary crate for the ESP32 implementing a water meter controller."
repository = "https://github.com/ivmarkov/esp32-water-meter"
readme = "README.md"

[features]
default = ["experimental", "native", "espidf"]

espidf = []
native = ["esp-idf-sys/native"]
experimental = ["esp-idf-hal/experimental", "esp-idf-svc/experimental", "embedded-svc/experimental"]

[dependencies]
anyhow = "1"
log = "0.4"
smol = "1.2"
async-broadcast = "0.3.4"
futures = {version = "0.3", features = ["async-await"] }
embedded-hal = { version = "0.2" }
embedded-svc = { version = "0.17.3" }
esp-idf-sys = { version = "0.30", features = ["binstart"] }
esp-idf-svc = { version = "0.37.2" }
esp-idf-hal = { version = "0.33.1" }
embedded-graphics = "0.7"
display-interface = "0.4"
display-interface-spi = "0.4"
st7789 = "0.6"
ruwm = { version = "0.1", path = "../ruwm" }
ruwm-std = { version = "0.1", path = "../ruwm-std" }

[build-dependencies]
embuild = { version = "0.28.2", features = ["espidf"] }
anyhow = "1"
