[package]
name = "ruwm-esp32"
version = "0.1.0"
authors = ["ivmarkov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["hal", "embedded"]
description = "A binary crate for the ESP32 implementing a water meter controller."
repository = "https://github.com/ivmarkov/esp32-water-meter"
readme = "README.md"

[features]
default = ["experimental"]

native = ["esp-idf-sys/native"]
experimental = ["esp-idf-hal/experimental", "esp-idf-svc/experimental", "embedded-svc/experimental"]

[dependencies]
anyhow = "1"
log = "0.4"
embedded-hal = { version = "0.2" }
embedded-svc = { version = "0.16.7" }
esp-idf-sys = { version = "0.30", features = ["binstart"] }
esp-idf-svc = { version = "0.36.9" }
esp-idf-hal = { version = "0.32.9" }
ruwm = { version = "0.1", path = "../ruwm" }

[build-dependencies]
embuild = { version = "0.28.2", features = ["espidf"] }
anyhow = "1"
