name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '50 4 * * *'

env:
  rust_toolchain: nightly

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Setup | Std
        run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default ${{ env.rust_toolchain }}
      - name: Setup | Trunk
        run: cargo install trunk
      - name: Build Web | Fmt Check
        run: cd ruwm-web; cargo fmt -- --check
#      - name: Build Web | Clippy
#        run: cd ruwm-web; cargo clippy --no-deps -- -Dwarnings
      - name: Build Web | Compile
        run: cd ruwm-web; trunk build --release
      - name: Build | Fmt Check
        run: cargo fmt -- --check
#      - name: Build | Clippy
#        run: export RUWM_WIFI_SSID=; export RUWM_WIFI_PASS=; export ESP_IDF_SDKCONFIG_DEFAULTS=$(pwd)/sdkconfig.defaults; cargo clippy --no-deps --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort -- -Dwarnings
      - name: Build | Compile
        run: export RUWM_WIFI_SSID=; export RUWM_WIFI_PASS=; export ESP_IDF_SDKCONFIG_DEFAULTS=$(pwd)/sdkconfig.defaults; cargo build --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
